check:
  - thoth-precommit
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-minimal-notebook:v0.0.7"
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: s2i-scipy-notebook
  registry-secret: thoth-station-thoth-pusher-secret
