host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: f33
    operating_system:
      name: fedora
      version: "33"
    python_version: "3.9"
    recommendation_type: latest

managers:
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - harshad16
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
